Added PlayAlbum and PlayPlaylist
brianstrauch/spotify pull request #4
Opened 2021-07-17 09:10 UTC by Threpio

Added:
api.PlayAlbum(deviceID, AlbumURI)
api.PlayPlaylist(deviceID, PlaylistURI)

These are required for spotify-cli issue: [#27](https://github.com/brianstrauch/spotify-cli/issues/27)

These allow for the request sent to the API to include the context_uri field that is required for the album and playlist play requests. Using the api.Play() resulted in the following error: `Unsupported uri kind: playlist_v2Error: Unsupported uri kind: playlist_v2`

2021-07-17 09:28 UTC, Threpio commented
<img width="916" alt="Screenshot 2021-07-17 at 11 27 22" src="https://user-images.githubusercontent.com/49570057/126032641-b6bd394a-a635-48fb-99e0-fae2addd6ceb.png">
Hilariously - When testing the cli out (by pointing it to this branch locally) It always showed the previous song that was being played before the playlist switch?
Nor sure where I have gone wrong...

2021-07-17 17:18 UTC, brianstrauch requested changes
Looks good, although I'd rather combine this new functionality with the existing `Play()` command to match the format of https://developer.spotify.com/documentation/web-api/reference/#endpoint-start-a-users-playback. I left one comment below.

2021-07-17 17:18 UTC, brianstrauch commented on player.go
> +		URIs string `json:"context_uri"`
Let's combine this function with the `Play()` function, passing it in as an extra argument. The header might look like this:

```
func (a *API) Play(deviceID, contextURI string, uris ...string) error
```

2021-07-17 17:22 UTC, brianstrauch commented
> It always showed the previous song that was being played before the playlist switch
> It only seems to happen some time. Guess it is how long it takes for the api to update.

This issue sounds like it might have to do with the logic here: https://github.com/brianstrauch/spotify-cli/blob/6bfc0a5f4ed77918a9043f5ac04628f20a05e0cc/internal/play/play.go#L70-L73

I can take a closer look when you make a PR for the CLI.

2021-07-17 18:24 UTC, Threpio commented
Combining it with the play functionality is a good idea.

Do we want to pass through the URI's as the same variable and then set a 'context_uri' flag or how should I go about it?

2021-07-17 19:47 UTC, brianstrauch commented
For the CLI commands, the user should pass the name with the `--playlist` or `--album` flag, call either the `GetPlaylists()` or `Search()` commands to get the URI, then pass that into `Play()`

2021-07-18 11:49 UTC, closed without merging

2021-07-18 11:49 UTC, Threpio commented
This PR and it's context will be refactored and merged within PR #5